apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployement-apache
  labels:
    app: apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache-pod
  template:
    metadata:
      labels:
        app: apache-pod
    spec:
      containers:
      - image: nico916/projet-m2:latest
        name: hello-cont
        ports:
        - containerPort: 49160
